theme = "tokyonight"

[editor]
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal."space"]
o = ":sh kitty --title 'i3floati3' -e lazygit 2>/dev/null" # TODO: Add label "Open Lazygit" 

[keys.normal]
esc    = ["collapse_selection", "keep_primary_selection"]
